#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Ejecutar Prettier para verificar el formato de los archivos
npx prettier --check .

# Ejecutar ESLint para verificar problemas de estilo
npx eslint . --fix

# Ejecutar pruebas (opcional, si tienes configurado npm test)
npm test

